version: '3.4'

services:
  dataapidocker:
    image: dataapidocker:dev
    container_name: DataAPIDocker
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "DataAPIDocker"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_dataapidocker$
    volumes:
      - C:\Users\saroj singh\source\repos\EFCoreInDocker_BASTA2019\DataAPI_SQLContainer\DataAPIDocker:/app
      - C:\Users\saroj singh\source\repos\EFCoreInDocker_BASTA2019\DataAPI_SQLContainer:/src
      - C:\Users\saroj singh\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_dataapidocker$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_dataapidocker$ \"\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true